[packages]
install = [
  "bc",
  "binutils",
  "compat-libcap1",
  "compat-libstdc++-33",
  "elfutils-libelf",
  "elfutils-libelf-devel",
  "gcc",
  "gcc-c++",
  "glibc",
  "glibc-devel",
  "ksh",
  "libaio",
  "libaio-devel",
  "libnsl",
  "libnsl.i686",
  "libgcc",
  "libstdc++",
  "libstdc++-devel",
  "make",
  "net-tools",
  "nfs-utils",
  "python",
  "python-configshell",
  "python-rtslib",
  "python-six",
  "smartmontools",
  "sysstat",
  "unixODBC",
  "unixODBC-devel",
  "targetcli",
]

[[groups]]
name = "oinstall"

[[groups]]
name = "dba"

[[users]]
name = "oracle"
primary_group = "dba"
supplementary_groups = ["oinstall"]
home = "/oracle"

[[users]]
name = "fmw"
primary_group = "dba"
supplementary_groups = ["oinstall"]
home = "/fmw"

[paths]
data_root = "/oradata"
profile_dir = "/etc/profile.d"
ora_inventory = "/etc/oraInst.loc"
oratab = "/etc/oratab"

[database]
target_version = "19c"
